SchoolManagementApplication/SchoolManagementApplication/Controllers/ModuleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SchoolManagementApplication.Data;
using SchoolManagementApplication.Models;

namespace SchoolManagementApplication.Controllers
{
    public class ModuleController : Controller
    {
        public ApplicationDbContext _db;
        public ModuleController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Module> ModulesList = _db.modules;
            return View(ModulesList);
        }
        //GET
        public IActionResult Create()
        {
            ViewData["CodeSector"] = new SelectList(_db.sectors, "Code", "Code");
            return View();
        }
        //SET
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Module obj)
        {
            _db.Add(obj);
            _db.SaveChanges();
            TempData["success"] = "Module created succefully";
            return RedirectToAction("Index");
        }
        //GET
        public IActionResult Edit(string code)
        {
            if (code == null)
            {
                return NotFound();
            }
            var ModuleFromDb = _db.modules.Find(code);
            if (ModuleFromDb == null)
            {
                return NotFound();
            }
            return View(ModuleFromDb);
        }
        //SET
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(Module obj)
        {
            _db.Update(obj);
            _db.SaveChanges();
            TempData["success"] = "Module Edited succefully";
            return RedirectToAction("Index");
        }
        //GET
        public IActionResult Delete(string code)
        {
            if (code == null)
            {
                return NotFound();
            }
            var ModuleFromDb = _db.modules.Find(code);
            if (ModuleFromDb == null)
            {
                return NotFound();
            }
            return View(ModuleFromDb);
        }
        //SET
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Delete(Module obj)
        {
            _db.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Module deleted succefully";
            return RedirectToAction("Index");
        }
    }
}

SchoolManagementApplication/SchoolManagementApplication/Controllers/SectorsController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolManagementApplication.Data;
using SchoolManagementApplication.Models;

namespace SchoolManagementApplication.Controllers
{
    public class SectorsController : Controller
    {
        public ApplicationDbContext _db;
        public SectorsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Sector> StudentsList = _db.sectors;
            return View(StudentsList);
        }
        //GET
        public IActionResult Create()
        {
            return View();
        }
        //SET
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Sector obj)
        {
            if (ModelState.IsValid)
            {
                _db.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Sector created succefully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        public IActionResult Edit(string code)
        {
            if (code == null)
            {
                return NotFound();
            }
            var SectorFromDb = _db.sectors.Find(code);
            if (SectorFromDb == null)
            {
                return NotFound();
            }
            return View(SectorFromDb);
        }
        //SET
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(Sector obj)
        {
            if (ModelState.IsValid)
            {
                _db.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Sector created succefully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        public IActionResult Delete(string code)
        {
            if (code == null)
            {
                return NotFound();
            }
            var SectorFromDb = _db.sectors.Find(code);
            if (SectorFromDb == null)
            {
                return NotFound();
            }
            return View(SectorFromDb);
        }
        //SET
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Delete(Sector obj)
        {
            _db.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Sector deleted succefully";
            return RedirectToAction("Index");
        }
    }
}

SchoolManagementApplication/SchoolManagementApplication/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchoolManagementApplication.Data;
using SchoolManagementApplication.Models;

namespace SchoolManagementApplication.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.students.Include(s => s.Sector);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            ViewData["CodeSector"] = new SelectList(_context.sectors, "Code", "Code");
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Age,CodeSector")] Student student)
        {
            _context.Add(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.students == null)
            {
                return NotFound();
            }

            var student = await _context.students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            ViewData["CodeSector"] = new SelectList(_context.sectors, "Code", "Code", student.CodeSector);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Age,CodeSector")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }
            _context.Update(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.students == null)
            {
                return NotFound();
            }

            var student = await _context.students
                .Include(s => s.Sector)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.students == null)
            {
                return Problem("Entity set 'ApplicationDbContext.students'  is null.");
            }
            var student = await _context.students.FindAsync(id);
            if (student != null)
            {
                _context.students.Remove(student);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
          return (_context.students?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

SchoolManagementApplication/SchoolManagementApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolManagementApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/BootsWatchTheme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolManagementApplication.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css"
    />
    @*swiper style :*@
    <style>
      .swiper {
        width: 100%;
        height: 100%;
      }

      .swiper-slide {
        text-align: center;
        font-size: 18px;
        background: #fff;

        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
      }

      .swiper-slide img {
        display: block;
        width: 100%;
        height: 100%;
        object-fit: cover;
      }
      .container1{
          height:600px;
      }

      .DivHover : hover{
          transform: translateY(-15px);
      }
    </style>


</head>
<body class="d-flex flex-column min-vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SchoolManagementApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sectors" asp-action="Index">Sectors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Module" asp-action="Index">Modules</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-xxl">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notification"/>
        </main>
    </div>

    <footer class="border-top footer text-muted mt-auto" style="position: initial;">
        <div class="container">
            &copy; 2022 - SchoolManagementApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SchoolManagementApplication/SchoolManagementApplication/Views/Shared/_Notification.cshtml
@if(TempData["success"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}